name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK and Gradle
        uses: ./.github/actions/setup-jdk-gradle
      - name: Lint debug build
        run: gradle :app:lintDebug --stacktrace
      - name: Run unit tests
        run: gradle :app:testDebugUnitTest --stacktrace
      - name: Build debug APK
        run: gradle :app:assembleDebug --stacktrace
      - name: Build release APK
        run: gradle :app:assembleRelease --stacktrace
